### ISSUE TITLE
KeyError: 'value' when no optional input is given while running Argus in action mode.

### ISSUE THREAD

**Issue by jiangnanpro** [purs3lab/Argus#6]
As in the example `python3 argus.py  --mode action --url https://github.com/actions-js/push.git`, the program will throw a KeyError when executing fuction `save_report_to_file()` within `argus.py` (line 80), details can be found as following:

```
  File "/root/argus.py", line 80, in main
    action.save_report_to_file()
  File "/root/argus_components/action.py", line 84, in save_report_to_file
    file_name = RESULTS_FOLDER / f"{self.action_name}_{self.options_dict['value']}.sarif"
                                                       ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'
```

In this scenario, both variables `option_provided` and `option_value` will be `None`, resulting in `option_dict` being an empty dictionary, which eventually raises the KeyError.

Maybe an if-condition should be added to the function `save_report_to_file(self)` for cases where no option is defined to prevent this issue, something like:

```
def save_report_to_file(self):
    if self.options_dict:
        file_name = RESULTS_FOLDER / f"{self.action_name}_{self.options_dict['value']}.sarif"
    else:
        file_name = RESULTS_FOLDER / f"{self.action_name}.sarif"
        
    return self.report.get_report(file_name)
```

 Or is there something that I'm missing?

**Comment by R3x** [comment]
Thanks! Should be fixed with my changes! We can reopen this if it still fails

**Comment by jiangnanpro** [comment]
Problem solved! ARGUS is now working smoothly :) Thanks for your effort!

Btw, as a PhD student, I'm interested in your dataset and have submitted a request through the Google form. Could you please check it out on your spare time? Thanks again!
